INSERT INTO Currencies (isocode,rate,version) VALUES ('USD',1.1847,1);
INSERT INTO Currencies (isocode,rate,version) VALUES ('JPY',133.37,1) ;
INSERT INTO Currencies (isocode,rate,version) VALUES ('IDR',16008.85,1);
INSERT INTO Currencies (isocode,rate,version) VALUES ('SEK',9.9680,1) ;
INSERT INTO Currencies (isocode,rate,version) VALUES ('AUD',1.5512,1);
INSERT INTO Currencies (isocode,rate,version) VALUES ('CNY',7.8356,1);
INSERT INTO Currencies (isocode,rate,version) VALUES ('TRY',4.5823,1);
INSERT INTO Currencies (isocode,rate,version) VALUES ('GBP',0.88183,1);
INSERT INTO Currencies (isocode,rate,version) VALUES ('CAD',1.4966,1);
INSERT INTO Currencies (isocode,rate,version) VALUES ('NZD',1.7193,1);
INSERT INTO Currencies (isocode,rate,version) VALUES ('EUR',1.0, 1);